Ntswdp 53 feat select level
Nice-HUD/Spacebar pull request #17
Opened 2024-11-22 02:30 UTC by min5421

## 📝 PR 설명

레벨을 선택해서 플레이 할 수 있도록 기능을 추가했습니다.

## 🛠 주요 변경 사항

- Title Screen에서 플레이어 수를 선택한 후 레벨을 선택하여 플레이 할 수 있습니다.
- 게임 한 판이 끝난 후 Receipt Screen에서 
     next level을 선택하면 다음 레벨로 넘어가고, 
     change level을 선택하면 레벨을 선택하여 플레이 할 수 있고, 
     main menu를 선택하면 Title Screen으로 나옵니다.

## 🧪 테스트 체크리스트

- [ ] Title Screen에서 플레이어 수를 선택 후 레벨 변경이 가능한지 확인
- [ ] Receipt Screen에서 다음 레벨로 넘어가기, 레벨 변경, title 화면으로 돌아가기가 가능한지 확인

## 📸 스크린샷 또는 비디오

![level_main](https://github.com/user-attachments/assets/0b932222-89f3-4fde-a270-9b2a26a44df3)
![level_receipt](https://github.com/user-attachments/assets/964d6cd1-f5c5-4e11-aae8-61f37f0d143d)

## 🔗 관련 Jira 이슈

NTSWDP-53

## ➕ 추가 사항

테스트 코드 개선에 대한 도움을 요청합니다.
현재 Title Screen에 대한 테스트 코드만 존재하고 Receipt Screen에 대한 테스트는 추가 해야 합니다.

## ✅ 체크리스트
- [ ] 코드 컨벤션을 준수했습니다
- [ ] 불필요한 코드를 제거했습니다
- [ ] 주석 처리를 필요한 만큼 하였습니다.
- [ ] PR 제목 또는 설명에 Jira 이슈 키를 포함했습니다

## 📑 P-n룰 설명
### comment남기실 때 P-n규칙 꼭 남겨주세요!
- P1: 꼭 반영해주세요 (Request changes)
- P2: 적극적으로 고려해주세요 (Request changes)
- P3: 웬만하면 반영해 주세요 (Comment)
- P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- P5: 그냥 사소한 의견입니다 (Approve)

2024-11-22 04:06 UTC, kojesung requested changes

2024-11-22 04:06 UTC, kojesung commented on src/test/java/screen/SelectLevelTest.java
> +        titleScreen.setReturnCode(7);
현재 빌드가 정상적으로 작동되지 않는데 titleScreen의 요소 때문인 거 같습니다! 확인해보시고 수정해주시거나 로컬에서만 확인하고 주석처리하고 올리는 방법 중 골라서 진행하시면 될 거 같습니다

2024-11-22 04:06 UTC, kojesung commented on src/test/java/screen/SelectLevelTest.java
> +        titleScreen.setSelectedLevel(3);;
여기랑 81번째 줄도 60번째 줄이랑 같은 이유로 문제가 발생하고 있는 것 같습니다

2024-11-22 07:46 UTC, min5421 commented on src/test/java/screen/SelectLevelTest.java
> +        titleScreen.setReturnCode(7);
testSelectLevel() 메소드를 전부 주석처리 해버렸는데 이러면 잘 작동 하나요?
그리고 titleScreen의 요소 때문에 정상적으로 작동되지 않는다는 것을 어떻게 찾아냈는지에 대한 상세한 설명을 요청 해도 될까요? 수정할 때 참고하겠습니다.

2024-11-22 08:10 UTC, kojesung commented on src/test/java/screen/SelectLevelTest.java
> +        titleScreen.setReturnCode(7);
에러 내용은 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f4672fd2-3ac8-4bca-91ad-4bbe239433f5">
이부분 들어가서 확확인해보시면 돼요!
브랜치에 push하면 자동으로 PR 업데이트 되면서 빌드 테스트 진행하니 에러 내용 하나씩 고치면서 확인해보시면 될 거 같습니다 일단 현재는 아직 에러나고 있어요!

2024-11-23 19:00 UTC, min5421 commented on src/test/java/screen/SelectLevelTest.java
> +        titleScreen.setReturnCode(7);
로컬에서는 현재 test도 3개 모두 통과하고 빌드도 잘 되는데, PR 올리고 진행되는 빌드 테스트는 왜 에러가 뜨는지 원인을 모르겠네요. 일단 전부 주석 처리했습니다.

2024-11-24 09:08 UTC, kojesung approved these changes
LGTM 기능 개발하시느라 고생하셨습니다!

2024-11-24 14:22 UTC, LeeHyunWoo02 approved these changes
오류 해결하시느라 고생하셨습니다.
LGTM!

2024-11-25 01:07 UTC, merged

2024-11-25 14:14 UTC, aeioiie reviewed
LGTM!

2024-11-25 14:14 UTC, aeioiie commented on src/test/java/screen/SelectLevelTest.java
> +        titleScreen.setSelectedLevel(7);;
P5: titleScreen.setSelectedLevel();; 부분들에서 세미콜론이 하나 더 입력된 것 같습니다!

2024-11-25 14:14 UTC, aeioiie commented on src/main/java/screen/TitleScreen.java
> +    public void setInputDelay(Cooldown inputDelay){this.inputDelay = inputDelay;};
P5: 이부분도 마지막에 세미콜론 하나 더 추가되었습니다