Ntswdp 65  settings resolution
Nice-HUD/Spacebar pull request #21
Opened 2024-11-25 16:12 UTC by LeeHyunWoo02

## 📝 PR 설명
해상도 설정 기능을 추가했습니다.

## 🛠 주요 변경 사항
- 해상도 설정 기능 관련 로직 추가
- 해상도 선택시 Frame과 Core에 수정사항이 잘 작동되는지 Test 코드 작성
- 설정된 해상도에 맞게 동적으로 UI 그려지기 위한 로직 추가

## 🧪 테스트 체크리스트
- 게임 실행 후, 설정 창에서 해상도가 잘 선택이 되는지 확인 ( 왼쪽 오른쪽 키 )
- 설정창에서 엔터(enter)키 누르면 해당 해상도로 바뀌는지 확인
- esc 눌러서 메인홈으로 이동했을 때 UI 해상도에 맞게 바뀌었는지 확인

## 📸 스크린샷 또는 비디오

![image](https://github.com/user-attachments/assets/841a9464-ce96-4c96-a2b8-f8451c96e875)

![image](https://github.com/user-attachments/assets/034d261e-305b-4556-8aa8-c245ab245219)

![image](https://github.com/user-attachments/assets/d5209b46-d540-40bf-8819-13984d3b11ef)

## 🔗 관련 Jira 이슈

PROJECT-65

## ➕ 추가 사항

게임을 실행해보면 게임 내 UI는 해상도에 맞게 업데이트가 안됩니다.
![image](https://github.com/user-attachments/assets/6922e5b0-d5ba-4d5f-adc4-4fc939a08ec4)

이 부분은 따로 백로그 생성해서 develop 해야 할 것 같습니다. 

## ✅ 체크리스트
- [ ] 코드 컨벤션을 준수했습니다
- [ ] 불필요한 코드를 제거했습니다
- [ ] 주석 처리를 필요한 만큼 하였습니다.
- [ ] PR 제목 또는 설명에 Jira 이슈 키를 포함했습니다

## 📑 P-n룰 설명
### comment남기실 때 P-n규칙 꼭 남겨주세요!
- P1: 꼭 반영해주세요 (Request changes)
- P2: 적극적으로 고려해주세요 (Request changes)
- P3: 웬만하면 반영해 주세요 (Comment)
- P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- P5: 그냥 사소한 의견입니다 (Approve)

2024-11-25 16:38 UTC, DongWonLee2 requested changes
P1 : 현재 충돌이슈가 있습니다. 충돌 해결 해주세요!

2024-11-26 03:24 UTC, kojesung requested changes
workflow파일의 영향을 받지 않는 상황입니다!
develop에 적용시켰을 때 문제가 발생할 수 있기 때문에
1. 현재 브랜치의 타겟 브랜치(출처)가 develop브랜치인지 확인해주세요!
2. 현재 브랜치가 생성된 시점이 workflow가 생성되기 이전의 develop일 때라면 rebase하여 workflow를 반영해주세요!

2024-11-26 03:27 UTC, LeeHyunWoo02 commented
> P1 : 현재 충돌이슈가 있습니다. 충돌 해결 해주세요!

해결 했습니다. 확인해주세요!

2024-11-26 03:32 UTC, LeeHyunWoo02 commented
> workflow파일의 영향을 받지 않는 상황입니다! develop에 적용시켰을 때 문제가 발생할 수 있기 때문에
> 
> 1. 현재 브랜치의 타겟 브랜치(출처)가 develop브랜치인지 확인해주세요!
> 2. 현재 브랜치가 생성된 시점이 workflow가 생성되기 이전의 develop일 때라면 rebase하여 workflow를 반영해주세요!

넵 확인했습니다.

2024-11-26 03:33 UTC, kojesung commented
> > workflow파일의 영향을 받지 않는 상황입니다! develop에 적용시켰을 때 문제가 발생할 수 있기 때문에
> > 
> > 1. 현재 브랜치의 타겟 브랜치(출처)가 develop브랜치인지 확인해주세요!
> > 2. 현재 브랜치가 생성된 시점이 workflow가 생성되기 이전의 develop일 때라면 rebase하여 workflow를 반영해주세요!
> 
> 넵 확인했습니다.

develop 반영 후 빌드 테스트 돌아가는 것 확인했습니다! 현재 테스트 통과는 되지 않고 있어서 통과되면 approve하겠습니다!

2024-11-26 03:35 UTC, LeeHyunWoo02 commented
> > > workflow파일의 영향을 받지 않는 상황입니다! develop에 적용시켰을 때 문제가 발생할 수 있기 때문에
> > > 
> > > 1. 현재 브랜치의 타겟 브랜치(출처)가 develop브랜치인지 확인해주세요!
> > > 2. 현재 브랜치가 생성된 시점이 workflow가 생성되기 이전의 develop일 때라면 rebase하여 workflow를 반영해주세요!
> > 
> > 
> > 넵 확인했습니다.
> 
> develop 반영 후 빌드 테스트 돌아가는 것 확인했습니다! 현재 테스트 통과는 되지 않고 있어서 통과되면 approve하겠습니다!

네. 감사합니다!

2024-11-26 04:37 UTC, min5421 requested changes

2024-11-26 04:37 UTC, min5421 commented on src/main/java/engine/Core.java
>  }
P1: '}' 하나 지워야 될 것 같아요!

2024-11-26 07:41 UTC, LeeHyunWoo02 commented on src/main/java/engine/Core.java
>  }
> Member

감사합니다.

2024-11-26 09:37 UTC, LeeHyunWoo02 commented on src/main/java/engine/Core.java
>  }
> P1: '}' 하나 지워야 될 것 같아요!

![image](https://github.com/user-attachments/assets/c6d8f1ad-c37d-4af7-a8ee-423b46f6d3f6)

음... 확인해보니까 '}'  문제가 없어보이네요..!

2024-11-28 04:15 UTC, kojesung approved these changes

2024-11-28 04:15 UTC, kojesung commented on src/test/java/screen/FrameTest.java
> +        frameMock = mock(Frame.class);
테스트 코드 관련 에러로 인한 빌드 실패 해결된 것 확인하여 approve하겠습니다

2024-11-28 05:36 UTC, dltnals1210 approved these changes
P3: 나중에 게임 ui 관련해서 개선하실 때, 메서드에 주석도 달아주시면 좋을 것 같습니다!

PR에 적힌 부분까지 정상적으로 run 되는 것과, 테스트 코드가 success 되는 것을 확인했습니다. 수고하셨습니다. LGTM.

2024-11-28 05:48 UTC, yunsful approved these changes
정말 고생하셨습니다.. LGTM

2024-11-28 05:59 UTC, LeeHyunWoo02 commented on src/test/java/screen/FrameTest.java
> +        frameMock = mock(Frame.class);
> 테스트 코드 관련 에러로 인한 빌드 실패 해결된 것 확인하여 approve하겠습니다

감사합니다!!

2024-11-28 06:13 UTC, DongWonLee2 approved these changes
LGTM!

2024-11-29 12:49 UTC, merged