[#97] 적 함선이 맨 아래쪽 화면에 도달했을 때 게임 오버
Nice-HUD/Spacebar pull request #22
Opened 2024-11-25 16:57 UTC by aeioiie

## 📝 PR 설명

게임 플레이 중 적 함선이 맨 아래쪽 화면의 선에 닿았을 때 게임이 종료되도록 하였습니다.

## 🛠 주요 변경 사항

- 게임 종료 관련 테스트 코드 추가
- 적 함선이 아래쪽 선과 닿을 때 게임 오버 관련 로직 구현

## 🧪 테스트 체크리스트

- [ ] 게임 실행
- [ ] 게임 플레이
- [ ] 모든 레벨에서 처치에 실패하고 적 함선이 맨 아래쪽으로 내려왔을 때 게임이 종료되는지 확인

## 📸 스크린샷 또는 비디오

https://github.com/user-attachments/assets/19f48762-736d-453f-b0ed-fdfb90c9eef7

## 🔗 관련 Jira 이슈

NTSWDP-97

## ➕ 추가 사항

## ✅ 체크리스트
- [ ] 코드 컨벤션을 준수했습니다.
- [ ] 불필요한 코드를 제거했습니다.
- [ ] 주석 처리를 필요한 만큼 하였습니다.
- [ ] PR 제목 또는 설명에 Jira 이슈 키를 포함했습니다.

## 📑 P-n룰 설명
### comment남기실 때 P-n규칙 꼭 남겨주세요!
- P1: 꼭 반영해주세요 (Request changes)
- P2: 적극적으로 고려해주세요 (Request changes)
- P3: 웬만하면 반영해 주세요 (Comment)
- P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- P5: 그냥 사소한 의견입니다 (Approve)

2024-11-26 02:54 UTC, yunsful requested changes
P1 게임 오버 스크린은 ScoreScreen 클래스로 그리고 있습니다! 이부분 확인하셔서 코드 수정하면 될 것 같습니다!

2024-11-26 03:15 UTC, kojesung commented on src/main/java/screen/GameScreen.java
> +//        if (this.enemyShipFormation.hasEnemyReachedBottom(this.height - 65)) {
주석처리하신 부분은 어떤 의도로 하신거고 왜 남겨두신건지 알려주시면 감사하겠습니다!

2024-11-26 05:55 UTC, min5421 reviewed
P5: 
level1은 적이 바닥까지 내려오기 전에 총알이나 장애물에 맞아 죽어서 테스트하지 못 했습니다.
level3는 적이 바닥에 닿지 않고 좌우로 움직이기만 해서 테스트하지 않아도 될 것 같습니다.
나머지 레벨은 적이 바닥에 닿았을 때 게임이 종료되는 것을 확인했습니다.

2024-11-26 05:55 UTC, min5421 commented on src/main/java/screen/GameScreen.java
> +
P3: 여기를 
private void handleGameOver() {
        this.levelFinished = true; // 레벨 종료
        this.isRunning = false; // 게임 루프 종료
        this.logger.info("Game Over. Returning to main menu.");
    }
이렇게 변경하면 GAME OVER 화면이 뜨지 않는 문제는 해결 될 것 같습니다.

2024-11-26 06:21 UTC, aeioiie commented on src/main/java/screen/GameScreen.java
> +//        if (this.enemyShipFormation.hasEnemyReachedBottom(this.height - 65)) {
저 부분이 추가 사항에 말씀드린 제가 처음에 잘못 작성한 부분의 코드입니다! 그 아래 523번째 줄부터 작성한 코드가 새롭게 작성한 부분이고, 푸시 전에 삭제했어야 했는데 깜빡했네요. 삭제 후 다시 커밋하여 푸시하겠습니다!

2024-11-26 06:22 UTC, aeioiie commented
> P1 게임 오버 스크린은 ScoreScreen 클래스로 그리고 있습니다! 이부분 확인하셔서 코드 수정하면 될 것 같습니다!

감사합니다! 참고하여 수정하도록 하겠습니다.

2024-11-26 06:31 UTC, aeioiie commented on src/main/java/screen/GameScreen.java
> +
this.returnCode = 1; 코드만 없으면 바로 GAME OVER 화면이 뜨네요! 감사합니다!!!

2024-11-26 06:33 UTC, aeioiie commented
> > P1 게임 오버 스크린은 ScoreScreen 클래스로 그리고 있습니다! 이부분 확인하셔서 코드 수정하면 될 것 같습니다!
> 
> 감사합니다! 참고하여 수정하도록 하겠습니다.

민서님이 알려주신대로  handleGameOver() 메서드를 수정했더니 바로 게임 오버 화면이 떠서 굳이 ScoreScreen 클래스를 참고하지 않아도 될 것 같습니다!

2024-11-26 07:08 UTC, kojesung approved these changes
고생하셨습니다!

2024-11-26 07:55 UTC, DongWonLee2 approved these changes
짱이에요~~👍

2024-11-26 09:13 UTC, dltnals1210 approved these changes
코드에서 많은 고민이 보입니다! 수고하셨어요!

2024-11-27 06:28 UTC, yunsful approved these changes

2024-11-27 06:29 UTC, merged