[#102] pause test 코드 개선 및 pause 관련 메서드 주석 처리
Nice-HUD/Spacebar pull request #24
Opened 2024-11-27 07:50 UTC by dltnals1210

## 📝 PR 설명
해당 PR은 pause test 코드를 개선하고, pause 기능 관련 메서드를 javadoc 스타일로 주석 처리합니다.

## 🛠 주요 변경 사항
- PauseTest 커버리지를 높이고자 함
- pauseGame()이 호출됐을 때, 'R', 'Q', 'M'의 입력이 들어오면 관련 메서드가 호출되는지 테스트할 수 있도록 함.

## 🧪 테스트 체크리스트
- [ ] PauseTest 코드 실행
- [ ] All Task Success 확인

## 📸 스크린샷 또는 비디오

## 🔗 관련 Jira 이슈
NTSWDP-102

## ➕ 추가 사항

## ✅ 체크리스트
- [ ] 코드 컨벤션을 준수했습니다
- [ ] 불필요한 코드를 제거했습니다
- [ ] 주석 처리를 필요한 만큼 하였습니다.
- [ ] PR 제목 또는 설명에 Jira 이슈 키를 포함했습니다

## 📑 P-n룰 설명
### comment남기실 때 P-n규칙 꼭 남겨주세요!
- P1: 꼭 반영해주세요 (Request changes)
- P2: 적극적으로 고려해주세요 (Request changes)
- P3: 웬만하면 반영해 주세요 (Comment)
- P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- P5: 그냥 사소한 의견입니다 (Approve)

2024-11-27 11:35 UTC, kojesung requested changes

2024-11-27 11:35 UTC, kojesung commented on src/test/java/screen/PauseTest.java
> +        // KeyEvent 객체 생성
현재 빌드할 때 발생하는 에러인 HeadlessException가  GUI 컴포넌트를 테스트 환경에서 생성할 때 발생한다고 하는데
KeyEvent 생성 부분을 제거하고 대신 InputManager를 통해 직접 키 상태를 조작하여 해결해야할 것 같습니다

2024-11-28 05:08 UTC, dltnals1210 commented on src/test/java/screen/PauseTest.java
> +        // KeyEvent 객체 생성
로컬 환경에서는 빌드에 문제가 없어서 놓친 부분이었는데, 체크해주셔서 감사합니다! 
해당 사항 KeyEvent 생성시 생성되는 TextField 객체가 GUI를 사용해 문제였던 것 같습니다. 해당 객체 모의 객체로 처리하여 해결했으니 확인 부탁드립니다!

2024-11-28 05:42 UTC, yunsful approved these changes
태스트 코드가 꼼꼼히 잘 작성되어 진 것 같습니다 고생하셨어요!

2024-11-28 05:54 UTC, kojesung approved these changes

2024-11-28 05:54 UTC, kojesung commented on src/test/java/screen/PauseTest.java
> +                mockField, // 소스 객체 (이벤트가 발생한 컴포넌트)
변경사항 반영해주신 점 확인했습니다 고생하셨습니다!!

2024-11-29 01:04 UTC, dltnals1210 commented on src/test/java/screen/PauseTest.java
> +                mockField, // 소스 객체 (이벤트가 발생한 컴포넌트)
감사합니다!

2024-11-29 01:04 UTC, merged