[#96] 스킨 선택 기능 구현
Nice-HUD/Spacebar pull request #25
Opened 2024-11-30 13:12 UTC by yunsful

## 📝 PR 설명

사용자가 게임 시작 전 스킨을 선택 할 수 있는 기능 구현
## 🛠 주요 변경 사항

- 타이틀 화면에서 게임 화면 넘어가기 전 스킨을 선택할 수 있는 화면이 추가됨
- 스킨 선택시 인게임 함선의 그래픽이 변경됨

## 🧪 테스트 체크리스트

- [ ] 스킨 설정 화면에 들어가 지는지 확인
- [ ] 스킨 설정 화면에서 위아래 키로 선택 된 스킨이 보이는지 확인
- [ ] 스페이스바 입력시 선택된 스킨이 인게임에 적용되는지 확인

## 📸 스크린샷 또는 비디오

<img width="742" alt="image" src="https://github.com/user-attachments/assets/53cc3ddc-ad99-43a9-8ebd-96a707ccb59d">
<img width="742" alt="image" src="https://github.com/user-attachments/assets/d014f378-0fff-42d0-a3f8-db185665674c">

## 🔗 관련 Jira 이슈

[NTSWDP-96]
## ➕ 추가 사항

## ✅ 체크리스트
- [x] 코드 컨벤션을 준수했습니다
- [x] 불필요한 코드를 제거했습니다
- [x] 주석 처리를 필요한 만큼 하였습니다.
- [x] PR 제목 또는 설명에 Jira 이슈 키를 포함했습니다

## 📑 P-n룰 설명
### comment남기실 때 P-n규칙 꼭 남겨주세요!
- P1: 꼭 반영해주세요 (Request changes)
- P2: 적극적으로 고려해주세요 (Request changes)
- P3: 웬만하면 반영해 주세요 (Comment)
- P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- P5: 그냥 사소한 의견입니다 (Approve)

[NTSWDP-96]: https://hanyang-team-swdnt.atlassian.net/browse/NTSWDP-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-01 05:44 UTC, min5421 requested changes

2024-12-01 05:44 UTC, min5421 commented on src/main/java/engine/Core.java
> +					LOGGER.info("선택 화면 종료");
P2: 1인 모드에서 스킨을 선택한 후 2인 모드 스킨 선택 화면이 나오고 있습니다.
case 7과 case 8 각각 마지막 줄에 break; 를 넣어 해결하면 좋을 것 같습니다.

2024-12-01 05:58 UTC, kojesung requested changes

2024-12-01 05:58 UTC, kojesung commented on src/main/java/engine/DrawManager.java
> +		this.backBufferGraphics = backBufferGraphics;
캡슐화 원칙을 지키면서 getter/setter를 활용하는 것이 좋아보이는데 의도하셨거나 굳이 필요 없는 사항이면 approve하겠습니다!

2024-12-01 06:13 UTC, yunsful commented on src/main/java/engine/Core.java
> +					LOGGER.info("선택 화면 종료");
아 확인했습니다! 감사합니다.

2024-12-01 06:18 UTC, yunsful commented on src/main/java/engine/DrawManager.java
> +		this.backBufferGraphics = backBufferGraphics;
생성자 불필요해져서 삭제했습니다! 검토 감사합니다!

2024-12-01 06:28 UTC, LeeHyunWoo02 commented on src/main/java/engine/Core.java
![image](https://github.com/user-attachments/assets/3333ff44-d2c9-45f9-a9ea-62ec9d98d53b)

1인용 게임을 실행 했는데 2인용 게임으로 실행이 되네요..!!
스킨 변경은 잘 되는 것 확인했고 
다른 리뷰어분들이 말씀해주신 부분 외에는 괜찮은 것 같습니다.!

2024-12-01 06:34 UTC, min5421 approved these changes

2024-12-01 06:36 UTC, yunsful commented on src/main/java/engine/Core.java
혹시 어떠한 경우에 그렇게 되는지 알 수 있을까요? 로컬에서는 잘 실행돼서요ㅠ

2024-12-01 06:37 UTC, kojesung commented on src/main/java/engine/DrawManager.java
> +		this.backBufferGraphics = backBufferGraphics;
넵 반영해주셔서 감사합니다

2024-12-01 06:38 UTC, yunsful commented on src/main/java/engine/Core.java
아 좀 전에 수정을 해서 혹시 pull 땡겨서 똑같은 문제가 발생하면 말씀해 주세요!

2024-12-01 06:41 UTC, min5421 commented on src/main/java/engine/Core.java
> +					LOGGER.info("선택 화면 종료");
주석이 필요한 곳에 상세히 적혀있던 게 너무 좋았어요.
덕분에 문제 해결방안을 빠르게 찾을 수 있었던 것 같습니다. 감사합니다.

2024-12-01 07:01 UTC, dltnals1210 requested changes

2024-12-01 07:01 UTC, dltnals1210 commented on src/main/java/engine/DrawManager.java
> +			backBufferGraphics.drawRect(screen.getWidth() / 2 - 15, 465, 30, 30);
<img width="617" alt="ScreenShot 2024-12-01 오후 3 54 52" src="https://github.com/user-attachments/assets/2180ce6a-b6cc-4ece-91e7-4e1ac0e19b30">
<img width="810" alt="ScreenShot 2024-12-01 오후 3 45 30" src="https://github.com/user-attachments/assets/3582649b-c176-4b4b-9c51-290a98542f91">

P3: 현재 중복된 코드 라인이 33% 이상이라 소나클라우드에서 fail이 뜨고 있습니다! 아마 해당 코드 부분처럼 거의 동일한 조건문과 결과가 반복되어서 그런 것 같습니다. 해당 부분 확인해보시고, for 문을 사용해서 반복되는 부분을 처리하고 상수 값(7, 2 - 15, 465, 30 등)은 final로 상수 처리해주는 방향으로 해결하시면 될 것 같아요.

2024-12-01 07:32 UTC, LeeHyunWoo02 commented on src/main/java/engine/Core.java
아 pull 당겨오니까 해결됐습니다~!
수고하셨어요!!

2024-12-01 07:33 UTC, LeeHyunWoo02 approved these changes
수고하셨습니다.
LGTM

2024-12-01 08:30 UTC, dltnals1210 approved these changes
수고하셨습니다! LGTM

2024-12-01 09:41 UTC, kojesung approved these changes
수정사항 확인되어 approve합니다 고생하셨어요~!~!~!!!!

2024-12-02 06:34 UTC, aeioiie approved these changes
고생하셨습니다. LGTM!

2024-12-02 09:13 UTC, merged