[#64] 소리 조절 기능 구현
Nice-HUD/Spacebar pull request #26
Opened 2024-12-01 10:29 UTC by min5421

## 📝 PR 설명

setting에서 소리 크기를 조절 할 수 있도록 구현

## 🛠 주요 변경 사항

- setting 화면에 소리를 조절하는 칸이 생김
- 소리 크기 변경 시 바로 적용 됨

## 🧪 테스트 체크리스트

- [ ] setting에 들어가서 volume을 변경
- [ ] 게임을 플레이 했을 때 변경된 volume이 잘 적용 됐는지 확인

## 📸 스크린샷 또는 비디오

![sound](https://github.com/user-attachments/assets/09217aad-f7b3-429d-aaca-76ff4e4e2950)

## 🔗 관련 Jira 이슈

[NTSWDP-64]

## ➕ 추가 사항

첫 화면에서 레벨 선택할 때 레벨 숫자들이 위치가 이상해서 간단하게 수정했습니다.

## ✅ 체크리스트
- [ ] 코드 컨벤션을 준수했습니다
- [ ] 불필요한 코드를 제거했습니다
- [ ] 주석 처리를 필요한 만큼 하였습니다.
- [ ] PR 제목 또는 설명에 Jira 이슈 키를 포함했습니다

## 📑 P-n룰 설명
### comment남기실 때 P-n규칙 꼭 남겨주세요!
- P1: 꼭 반영해주세요 (Request changes)
- P2: 적극적으로 고려해주세요 (Request changes)
- P3: 웬만하면 반영해 주세요 (Comment)
- P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
- P5: 그냥 사소한 의견입니다 (Approve)

2024-12-02 02:18 UTC, yunsful reviewed
P4: 테스트에서 사용하는 SoundManager 클래스 생성자에 경로를 다루는 로직이 포함 되어 있어서 깃헙엑션 환경상 읽을 수 없어 발생하는 빌드 에러가 뜨는 것 같습니다.. 이부분 추후 이슈로 만들어야 할 것 같아 일단 주석 처리하는 걸 추천해요!

2024-12-02 02:18 UTC, yunsful commented on src/test/java/screen/SettingsScreenTest.java
>          settingsScreen = new SettingsScreen(800, 600, 60, frameMock);
이부분

2024-12-02 02:18 UTC, yunsful commented on src/test/java/screen/SoundControlTest.java
> +        soundManager = SoundManager.getInstance();
이부분

2024-12-02 02:18 UTC, yunsful approved these changes

2024-12-02 02:57 UTC, kojesung requested changes

2024-12-02 02:57 UTC, kojesung commented on src/test/java/screen/SoundControlTest.java
> +    public void setUp() {
여기 바로 밑 부분에
```
System.setProperty("java.awt.headless", "true");
```
추가해주실 수 있나요? CI 환경에서 GUI를 실험하려면 Headless 모드 설정을 해줘야한다고 하는 것 같습니다
이렇게 해도 안되면... Frame 관련된 내용 삭제하고(주석처리) 로컬에서 테스트 할 때만 주석 빼고 하는 방식으로 사용하고 올려야할 것 같습니다!

2024-12-03 00:04 UTC, min5421 commented on src/test/java/screen/SoundControlTest.java
> +    public void setUp() {
추가 했는데도 안 돼서 주석 처리 했습니다.

2024-12-03 02:29 UTC, kojesung approved these changes
변경사항 확인했습니다 고생하셨어요!

2024-12-03 06:33 UTC, dltnals1210 approved these changes
수고하셨습니다. LGTM!

2024-12-03 13:18 UTC, aeioiie approved these changes
수고하셨습니다. LGTM!

2024-12-04 08:20 UTC, merged